### ISSUE TITLE
Support for pseudo-class selectors?

### ISSUE THREAD

**Issue by rashadg1030** [hapytex/css-selectors#22]
Hello! Really happy that there is a library in the Haskell ecosystem for checking CSS selectors at compile-time. It's come in handy for a new project/"framework" that I'm working on, so thank you. Anyways, I was wondering if there's support for pseudo-class selectors like `:last-child`? I'd like to be able to do something like:

```haskell
[csssel|tr:last-child|]
```

**Comment by KommuSoft** [comment]
Not at the moment, but it is on the roadmap. I hope to find some time by the end of the year to implement this.

**Comment by KommuSoft** [comment]
This is merged into a new release.
